### ISSUE TITLE
[desktop_multi_window] Proposal: Add a `resizable` boolean setter to `WindowController`

### ISSUE THREAD

**Issue by GroovinChip** [MixinNetwork/flutter-plugins#101]
It would be nice to be able to control whether windows are allowed to be resizable or not.

Example:
```dart
windowController
  ..setFrame(const Offset(0, 0) & const Size(350, 350))
  ..center()
  ..setTitle('About {{app_name}}')
  ..isResizable(false) // This is what I'm suggesting
  ..show();
```

**Comment by Chappie74** [comment]
I support this as well. I want to prevent the user from resizing sub windows. Not sure if its possible though.

**Comment by GroovinChip** [comment]
Hello, is anyone able to provide an update about this? It's really an important feature for desktop apps. @boyan01 perhaps?

**Comment by GroovinChip** [comment]
https://stackoverflow.com/a/29339315/8819885
