### ISSUE TITLE
[pasteboard] Can I generate a png picture in the image function?

### ISSUE THREAD

**Issue by chifandeyu** [MixinNetwork/flutter-plugins#105]
It is to save a bitmap and I want a picture in png format.Then is there any way to do it?

**Comment by boyan01** [comment]
Yes, you can use `decodeImageFromList`.

Here is usuage:

https://github.com/MixinNetwork/flutter-app/blob/5c795a228e712a3adab3e790e438bcc11e74b6bf/lib/utils/system/clipboard.dart#L32-L57
