### ISSUE TITLE
[ogg_opus_player] Build in windows error

### ISSUE THREAD

**Issue by chifandeyu** [MixinNetwork/flutter-plugins#106]
flutter doctor:
```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [版本 10.0.17763.2928], locale zh-CN)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.15)
[!] Android Studio (not installed)
[√] VS Code (version 1.67.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

```
build error info:
```
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1900	“P1”(第“20211014”版)和“P2”(第“20210202”版)之间 Il 不匹配	ogg_opus_player	D:\workspace\github\flutter-plugins-custom\packages\ogg_opus_player\example\build\windows\plugins\ogg_opus_player\shared\LINK	1	
```

**Comment by boyan01** [comment]
https://stackoverflow.com/questions/8959973/il-mismatch-between-p1-version-20080116-and-p2-version-20070207


The [libs](https://github.com/MixinNetwork/flutter-plugins/blob/main/packages/ogg_opus_player/src/libs/windows_x64) in [ogg_opus_player] are compiled by Visual Studio 2022, so it seems make the library can not compile on Visual Studio 2019.

**Comment by chifandeyu** [comment]
> https://stackoverflow.com/questions/8959973/il-mismatch-between-p1-version-20080116-and-p2-version-20070207
> 
> The [libs](https://github.com/MixinNetwork/flutter-plugins/blob/main/packages/ogg_opus_player/src/libs/windows_x64) in [ogg_opus_player] are compiled by Visual Studio 2022, so it seems make the library can not compile on Visual Studio 2019.

Ok.I compiled the [libs](https://github.com/MixinNetwork/flutter-plugins/blob/main/packages/ogg_opus_player/src/libs/windows_x64) using vs2019 and it can run.
