### ISSUE TITLE
[desktop_drop] MacOS - Screenshot XFiles location

### ISSUE THREAD

**Issue by ollyde** [MixinNetwork/flutter-plugins#110]
When trying to read the file from a MacOS screenshot from the desktop, it errors.

1. Use the screenshot shortcut
2. Drag the instant screenshot into the app

Example of file
`/var/folders/p9/j8jkzc5j4cxfh3ckpvrg1f0h0000gn/T/TemporaryItems/NSIRD_screencaptureui_TPPuUM/Screenshot 2022-06-22 at 12.22.33.png`

<img width="1316" alt="Screenshot 2022-06-22 at 12 24 13" src="https://user-images.githubusercontent.com/6940726/175006945-88899e95-deed-479e-94f1-19e77c99c98c.png">

**Comment by ollydixon** [comment]
I found the error.
After dropping the file into the flutter app, it sends 2 files. The first file is invalid.

<img width="333" alt="Screenshot 2022-06-22 at 13 27 56" src="https://user-images.githubusercontent.com/6940726/175018388-36e03dea-b1b2-43b1-8fbf-5f0bac440ef9.png">

**Comment by boyan01** [comment]
The first invalid fileUrl read by `draggingPasteboard.readObjects(forClasses: [NSURL.self], options: searchOptions)`

https://github.com/MixinNetwork/flutter-plugins/blob/6b604ed71a53f1303fba4ba421ef13de1cb3f5bd/packages/desktop_drop/macos/Classes/DesktopDropPlugin.swift#L105-L110

But this was added in PR #73  which fixed #72. 

I don't know how to remove this I can not find any document for this, so let's keep this open till somebody could provider more help.
