### ISSUE TITLE
[desktop_webview_window][Linux] Webview missing required files

### ISSUE THREAD

**Issue by nathantaal** [MixinNetwork/flutter-plugins#113]
![image](https://user-images.githubusercontent.com/26705043/177483053-993579c0-26e2-4e71-9501-061b342ed801.png)

Note: I did run 'sudo apt install webkit2gtk-4.0' but the package could not be resolved so nothing got installed

**Comment by boyan01** [comment]
>  I did run `sudo apt install webkit2gtk-4.0` but the package could not be resolved so nothing got installed

So here is an error: `A required package was not found`.  looks OK

**Comment by nathantaal** [comment]
I did 'sudo apt-get install libwebkit2gtk-4.0-dev' instead as suggested [here](sudo apt-get install libwebkit2gtk-4.0-dev), but that didn't do anything

**Comment by nathantaal** [comment]
@boyan01 ...

**Comment by dhiep** [comment]
same
![image](https://user-images.githubusercontent.com/26452390/233335220-f16196b1-38f6-44d6-bc9d-c85a98f31c72.png)

**Comment by dIvYaNshhh** [comment]
is there any update, i am getting same error.
