### ISSUE TITLE
ogg_oplus_player from url

### ISSUE THREAD

**Issue by rafaellfmachado** [MixinNetwork/flutter-plugins#118]
Is possible, use ogg from url ?

Exemple:
https://filesmix.nyc3.digitaloceanspaces.com/sistema/2547/a2729ec1165f8a9c3faa16c3bc20a9479e20e912/1657366622-blob.ogg

or do you have an example that downloads and then plays?

**Comment by boyan01** [comment]
> Is possible, use ogg from url ?

It's impossible by using this package.  ogg_opus_player can play local ogg opus file only.
