### ISSUE TITLE
Could not get the correct file mimeType

### ISSUE THREAD

**Issue by leoelephant** [MixinNetwork/flutter-plugins#120]
onDragDone: (detail) async {
    setState(() {
        list.addAll(detail.files);
     });
    for (final file in detail.files) {
        debugPrint(file.mimeType);
    }
},

Then the console prints out null。
done: D:\XXX.jpg
flutter: null

What should I do to get the correct file type？
thx

**Comment by boyan01** [comment]
get file mimeType is not the function provided by this package.
