### ISSUE TITLE
Cookie Manager [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Areopagitics** [MixinNetwork/flutter-plugins#125]
A way to manage cookies for auto-login similar to the mobile version here https://pub.dev/documentation/webview_flutter/latest/webview_flutter/CookieManager-class.html.

**Comment by KRTirtho** [comment]
`desktop_webview_window` is using [ICoreWebView2](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2) for Windows, [WKWebView](https://developer.apple.com/documentation/webkit) for MacOS and [WebkitGTK](https://webkitgtk.org/) for Linux

All of these has Cookie management support through different APIs.

- [WebView2.CookieManager](https://webkitgtk.org/reference/webkit2gtk/stable/class.CookieManager.html) for WebkitGtk (linux)
- [ICoreWebView2CookieManager](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2cookiemanager?view=webview2-1.0.2478.35) for ICoreWebView2 (windows)
- [HTTPCookieStorage](https://developer.apple.com/documentation/foundation/httpcookiestorage) for WKWebView (macos)

So, it is possible to write and platform independent implementation covering all this for each specific platforms. The library already uses Method Channels to accomplish all the functionalities. It should just a few more rpc calls and responses and some extra Dart classes that abstracts them.
