### ISSUE TITLE
[Pasteboard] Did `Pasteboard.image` return the correct imageBytes?

### ISSUE THREAD

**Issue by annd22** [MixinNetwork/flutter-plugins#156]
Hi,

I'm currenty developing an flutter window application, my flow:

- Copy image from browser to clipboard -> use Pasteboard.image to get imageBytes ->use that imageBytes  to save the image to desktop

The problem is, I cannot get the file's extension (.png) with imageBytes.

I use `base64Encode` function of `dart:convert` to convert imageBytes to base64 string, and the first character of this string always starts with `Q`, instead `i` for png file.

Please help me with this case, or can you recommend a different way to get file's extension from imageBytes?

Thanks.

**Comment by boyan01** [comment]
The format of image which we got is BITMAP on windows, png on Linux/macOS. 

>  recommend a different way to get file's extension from imageBytes?

you can use `decodeImageFromList` to decode it to Image, and then convert it to any image format data.

> Copy image from browser to clipboard -> use Pasteboard.image to get imageBytes ->use that imageBytes to save the image to desktop

Here is some codes might that help you.

https://github.com/MixinNetwork/flutter-app/blob/a5cad9bdc698a05b6f78a3c863231844a86a3821/lib/utils/system/clipboard.dart#L32-L57

**Comment by annd22** [comment]
Hi @boyan01 , 

Thank for your helpful anwser, it helps me a lot.
