### ISSUE TITLE
[desktop_drop 0.3.3] Not working in Windows if running app as administrator

### ISSUE THREAD

**Issue by Wishmater** [MixinNetwork/flutter-plugins#161]
To reproduce: in any app working with dektop_drop, build it for Windows in release mode, then right click and select "Run as administrator". Now drag and drop doesn't work (shows the forbidden circle icon when dragging into the app).

**Comment by boyan01** [comment]
That's the feature of Windows.

Drag & Drop only works for programs that have the same permission level. If you run an application as admin, you can only drag and drop files from applications that also run as admin.

https://superuser.com/questions/1172989/why-doesnt-usual-dragdrop-work-in-windows-10

https://learn.microsoft.com/zh-cn/archive/blogs/patricka/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi

**Comment by Wishmater** [comment]
> That's the feature of Windows.

Wow, what a stupid "feature". Thanks Bill Gates.

Sorry for bothering you and thanks for the quick response.

**Comment by riccardo-runci** [comment]
any solution of that boring things?
