### ISSUE TITLE
[desktop_multi_window] do you plan to support flutter >= 3.1?

### ISSUE THREAD

**Issue by rustdesk** [MixinNetwork/flutter-plugins#165]
Thanks for you great job first.

**Comment by boyan01** [comment]
Sorry, what does the question meaning? 

Is there anything wrong on flutter 3.1+ ?

**Comment by cwangfr** [comment]
I think he's means crashed on version 3.3
New flutter beta version 3.6 no crashed anymore.

**Comment by rustdesk** [comment]
Yes, we have crash on 3.3.

**Comment by boyan01** [comment]
accrodding the comments , it seem the issue duplicated of #139, so I'll close this one.

the crash on Windows caused by flutter engine which has been fixed in latest master channel. see more: https://github.com/flutter/flutter/issues/110311

**Comment by rustdesk** [comment]
Thanks
