### ISSUE TITLE
When i drop a file into the web app, the browser opens another page to view the file

### ISSUE THREAD

**Issue by CesareIsHere** [MixinNetwork/flutter-plugins#166]
When i drop a file into the web app, the browser opens another page to view the file.
Basically the browser catch the file before the app, and opens it in a new page.
Why? Thanks!

**Comment by CesareIsHere** [comment]
Someone could help me please?

**Comment by RoyalCoder88** [comment]
Hi please I have the same problem, any ideas on how to fix it? Thanks!

**Comment by CesareIsHere** [comment]
Hi everyone,
did you tried to do this:

    void main() async {
        // Prevent context menu and drag and drop on web
        if (kIsWeb) {
               html.window.document.onDrop.listen((evt) => evt.preventDefault());
        }

        runApp(
          App()
        );
    }
