### ISSUE TITLE
Can embedded in one window not open a new window for macos ?

### ISSUE THREAD

**Issue by sugur** [MixinNetwork/flutter-plugins#167]
Can embedded in one window not open a new window for macos ?

**Comment by boyan01** [comment]
I guess you means the `desktop_webview_window` plugin

Sorry the answer is NO, that is impossible now. Duplicate of https://github.com/MixinNetwork/flutter-plugins/issues/30

You can track this issue for more information. https://github.com/flutter/flutter/issues/37597

**Comment by boyan01** [comment]
the macos version is tracked here: https://github.com/flutter/flutter/issues/41725

**Comment by sugur** [comment]
> I guess you means the `desktop_webview_window` plugin
> 
> Sorry the answer is NO, that is impossible now. Duplicate of #30
> 
> You can track this issue for more information. [flutter/flutter#37597](https://github.com/flutter/flutter/issues/37597)

Yes, but `desktop_webview_window` plugin cannot setup user_agent and set javsscript.
