### ISSUE TITLE
It doesn't work on MacOS

### ISSUE THREAD

**Issue by FN8087** [MixinNetwork/flutter-plugins#17]
No problem with windows,
It doesn't work on MacOS

**Comment by crossle** [comment]
Which one plugin?

**Comment by FN8087** [comment]
> 哪一个插件？

desktop_webview_window: ^0.0.5

**Comment by ashutosh2014** [comment]
> > Which one plugin?
> 
> desktop_webview_window: ^0.0.5
Desktop Web View for Macos also not working on my machine. I m getting this issue.
![Screenshot 2021-11-08 at 9 34 31 AM](https://user-images.githubusercontent.com/48257422/140682695-58427c37-fce5-4d7a-b127-b6198e93c7bb.png)

**Comment by boyan01** [comment]
Can you describe more details about you usage?

1. Is the example works on your computer?
2. OS verison?
3.  Flutter version?
4.  Which website are you browsing?
5. Is there any warning or errror log  print?

**Comment by boyan01** [comment]
> > > Which one plugin?
> > 
> > 
> > desktop_webview_window: ^0.0.5
> > Desktop Web View for Macos also not working on my machine. I m getting this issue.
> > ![Screenshot 2021-11-08 at 9 34 31 AM](https://user-images.githubusercontent.com/48257422/140682695-58427c37-fce5-4d7a-b127-b6198e93c7bb.png)

It seems the build error was caued by swift name shadowed. 

Thanks for your details, I will fix this soon.

**Comment by ashutosh2014** [comment]
> Can you describe more details about you usage?
> 
> 1. Is the example works on your computer?
> 2. OS verison?
> 3. Flutter version?
> 4. Which website are you browsing?
> 5. Is there any warning or errror log  print?

I'm building the example project.
OS Version - 10.15.7 

Flutter version:-Channel dev, 2.6.0-11.0.pre

**Comment by FN8087** [comment]
> Can you describe more details about you usage?
> 
> 1. Is the example works on your computer?
> 2. OS verison?
> 3. Flutter version?
> 4. Which website are you browsing?
> 5. Is there any warning or errror log  print?

MacOS 11.5.1 or 12.0
Flutter version:2.5.3
