### ISSUE TITLE
ogg_opus_player runing on emulator ios xcode ?

### ISSUE THREAD

**Issue by rafaellfmachado** [MixinNetwork/flutter-plugins#171]
There is already the possibility to run the plugin in the emulator.

Or if not, is there something to play as an exception to at least compile the app?

**Comment by rafaellfmachado** [comment]
no prediction?

**Comment by crossle** [comment]
Maybe m1 device emulator work well.

**Comment by rafaellfmachado** [comment]
Unfortunately, my mac is m1, and using ogg_opus_player, I can only debug directly on the device, still waiting for a solution.
