### ISSUE TITLE
Render as Widget

### ISSUE THREAD

**Issue by ashutosh2014** [MixinNetwork/flutter-plugins#19]
Can we rendered as widget rather than  opening in  another window?

**Comment by boyan01** [comment]
Do you meaning `desktop_webview_window`?

I have no idea to rendered a webview as widget on Windows and Linux.

**Comment by ashutosh2014** [comment]
Yess, desktop_webview_window
Do you have any idea about  rendering  a webview as widget on MACOS

**Comment by boyan01** [comment]
I have some ideas, but haven't test it yet.

Maybe we just migrate the flutter official iOS webview implementation to macOS.
 https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FlutterWebView.m

But there is another issue. flutter do not support `PlatformView` on macOS now.  https://github.com/flutter/flutter/issues/41722

I guess webview on macOS support offscreen render, so maybe we can render it by flutter `TextureWidget`. 
 ref: https://pub.dev/packages/webview_windows

----

It may be feasible or impossiable, and this is just an idea to implement webview widgets, and there must be a lot of difficulties in the implementation.
