### ISSUE TITLE
New frameless window

### ISSUE THREAD

**Issue by asmith20002** [MixinNetwork/flutter-plugins#190]
I'd like to use the new window as a full screen overlay. (to show media)

Is it possible to open it up frameless?

More info:
`bitsdojo_window` package sets a custom frame for the main flutter window app but the new window opened by `DesktopMultiWindow.createWindow` completely ignores the custom frame of `bitsdojo_window` and opens up a simple window.

Any solution for this situation?

**Comment by LeroyLaw** [comment]
I believe you can use another library called "windowManager" for that.

**Comment by asmith20002** [comment]
`window_manager` doesn't open up a new window. Did you mean using `window_manager` on top of this one?

**Comment by LeroyLaw** [comment]
Window_manager has several utilities, such as making the screen fullscreen, it also has a feature that you can remove the title bar, and set the window size, and so on. The idea was to use it in conjunction with desktop_multi_window.

**Comment by asmith20002** [comment]
I see. Well apparently we're close to the official release of flutter multi window support. I'll probably wait for that one. Thanks for the replies ;)

**Comment by LeroyLaw** [comment]
You have the official announcement of that, I wasn't aware of it.

**Comment by asmith20002** [comment]
You have probably seen the demo by now. Sharing the youtube preview just in case:

https://www.youtube.com/watch?v=vtB-teu57vw
