### ISSUE TITLE
[pasteboard] Rename `Pasteboard.image` to `Pasteboard.fileBytes`

### ISSUE THREAD

**Issue by Maksimka101** [MixinNetwork/flutter-plugins#194]
Hey, thanks for the package, it's solving my problem!

But when I started working with it I didn't understand that I can get the file bytes from the `Pasteboard.image`. It's not obvious to me. So if you'll rename this getter to the `fileBytes` it will be much more convenient and easier to understand

**Comment by boyan01** [comment]
Thansk for the advice, but It doesn't sounds good to me.

The `Pasteboard.image` only designed to get image data bytes. And the files path could obtain by `Pasteboard.files` , then you can read the bytes by dart io `File` apis .

**Comment by cosysoft-maksim-zemlyanikin** [comment]
But in the web I can read a file from the `Pasteboard.image` which sounds strange
