### ISSUE TITLE
[desktop_multi_window] createWindow fails with MissingPluginException

### ISSUE THREAD

**Issue by treeplate** [MixinNetwork/flutter-plugins#197]
(by the way, the template for issues report just says 'omething looks wrong', lacking an s)

## The Bug

When calling DesktopMultiWindow.createWindow(), i get:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method createWindow on channel mixin.one/flutter_multi_window)

## Reproduce Steps
1. call WidgetsFlutterBinding.ensureInitialized();
2. call DesktopMultiWindow.createWindow()

## Expected behavior

I expected it to create a hidden window.

**Version (please complete the following information):**
 - Flutter Version: Flutter 3.7.0-15.0.pre.16 • channel master
 - OS: macOS Monterey v12.5.1
 - plugin: [desktop_multi_window]

**Comment by treeplate** [comment]
multi_window has the same problem, so it might just be a Flutter 3.7.0-15.0.pre.16 bug...

**Comment by LeroyLaw** [comment]
I got the same problem, I have flutter version 3.3.10, so I don't think it's a flutter problem.

**Comment by Adrian-Samoticha** [comment]
Did you register the plugin in your `MainFlutterWindow.swift` file? The package's readme isn't very clear about this, but your `MainFlutterWindow.swift` file needs to look something like this (copied from example project):

```swift
import Cocoa
import FlutterMacOS
import desktop_multi_window
import desktop_lifecycle

class MainFlutterWindow: NSWindow {
  override func awakeFromNib() {
    let flutterViewController = FlutterViewController.init()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    RegisterGeneratedPlugins(registry: flutterViewController)
    
    FlutterMultiWindowPlugin.setOnWindowCreatedCallback { controller in
      // Register the plugin which you want access from other isolate.
      DesktopLifecyclePlugin.register(with: controller.registrar(forPlugin: "DesktopLifecyclePlugin"))
    }

    super.awakeFromNib()
  }
}
```

**Comment by treeplate** [comment]
ok, looks like SOMETHING fixed it, maybe updating computer?
