### ISSUE TITLE
Flutter SDK Version 大于 3.0.5的版本没法创建Window并show 出来

### ISSUE THREAD

**Issue by 769755893** [MixinNetwork/flutter-plugins#199]
平台是Windows，只有Flutter SDK 版本<=3.0.5才能成功创建window, Flutter的Windows平台上看起来C++的代码也没有变动什么，可能是引擎变动导致的吗，求助

**Comment by boyan01** [comment]
It seem the issue duplicated of https://github.com/MixinNetwork/flutter-plugins/issues/139

the crash on Windows caused by flutter engine which has been fixed in latest master channel. see more: https://github.com/flutter/flutter/issues/110311

**Comment by 769755893** [comment]
哦好的，谢谢你
