### ISSUE TITLE
[desktop_webview_window] is it possiable support runJavascriptReturningResult

### ISSUE THREAD

**Issue by dodatw** [MixinNetwork/flutter-plugins#21]
I want to catch html from webview on windows destop.
is it possible support :
https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewController/runJavascriptReturningResult.html

or is there have other solution ?

**Comment by boyan01** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1020.30#executescript  

According the document, the answer should be yes.

But this plugin haven't implement this yet.

**Comment by dodatw** [comment]
Is it possible add this function?
