### ISSUE TITLE
[desktop_drop] Unable to drop anymore

### ISSUE THREAD

**Issue by apoleo88** [MixinNetwork/flutter-plugins#214]
## Reproduce Steps
1. Clone the example and try to drop something.

## Expected behavior

Able to drop, but the mouse cursor transforms into the "prohibited sign" (I am unable to screenshot the mouse)

## Versions
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (2 days ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1

Windows 10 Pro 22H2
Build 19045.2546
Windows Feature Experience Pack 120.2212.4190.0

 - desktop_drop: 0.4.0

I tried with desktop_drop 3.0.0, with flutter 3.7.0 and 3.3.10 without success.
Everything was working fine before, maybe a windows update?

**Comment by boyan01** [comment]
What happen if you build the example with `flutter build windows`, and then open the `build\windows\runner\release\desktop_drop_example.exe` by explorer.


if only not working in debug mode, maybe this is relate to  #161

**Comment by apoleo88** [comment]
Yes, you are right. 
Lately I set my IDE to run as administrator.

**Comment by randal923** [comment]
Wow, what a dumb feature from Windows. I think this should be added to pub dev page to warn other Windows users.
