### ISSUE TITLE
Unhandled Exception: RangeError: Value not in range: 8

### ISSUE THREAD

**Issue by JesusJoseph** [MixinNetwork/flutter-plugins#217]
Getting exception when below line of code is executed. 
**List<int> allSubWindowIds = await DesktopMultiWindow.getAllSubWindowIds();**

**_Please note that this error occurs ONLY when there are no sub window opens at that time. If there are one or more sub window then NO issues._** 

## Expected behavior
I expected that this line of code will return null or a list with no items but not Exception

**Version (please complete the following information):**
 - Flutter Version: Flutter 3.7.3
 - OS: Windows 11
 - plugin: desktop_multi_window: ^0.2.0
 
## Full Exception
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError: Value not in range: 8
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:5213:5)
#1      _ByteBuffer.asInt64List (dart:typed_data-patch/typed_data_patch.dart:1988:5)
#2      _UnmodifiableByteBufferView.asInt64List (dart:typed_data-patch/typed_data_patch.dart:5690:43)
#3      ReadBuffer.getInt64List					serialization.dart:244
#4      StandardMessageCodec.readValueOfType			message_codecs.dart:513
#5      StandardMessageCodec.readValue				message_codecs.dart:479
#6      StandardMethodCodec.decodeEnvelope			message_codecs.dart:646
#7      MethodChannel._invokeMethod					platform_channel.dart:315	<asynchronous suspension>			
#8      DesktopMultiWindow.getAllSubWindowIds			desktop_multi_window.dart:76 	<asynchronous suspension>
#9      SongController.closeAllSubWindows				song_controller.dart:280	<asynchronous suspension>

**Comment by MegatronKing** [comment]
I have the same issue on Windows 10.

**Comment by yash-t-crest** [comment]
@MegatronKing @JesusJoseph I am also getting same issue have you any idea regarding this?

**Comment by holotrek** [comment]
Would love to get an answer to this too. This is happening to me on Windows 10. On MacOS it works fine and returns an empty list.

**Comment by wangdenkun** [comment]
the reason is “flutter::EncodableValue ≠ flutter::EncodableList ”
[i make a pr](https://github.com/MixinNetwork/flutter-plugins/pull/338)

**Comment by boyan01** [comment]
this should be closed by #338 , thanks for @wangdenkun

**Comment by omortie** [comment]
why this is not published on pub.dev yet?
