### ISSUE TITLE
desktop_webview_window in macos don't run

### ISSUE THREAD

**Issue by FN8087** [MixinNetwork/flutter-plugins#22]
![image](https://user-images.githubusercontent.com/90084202/141396123-146e2e45-7a4b-453b-808b-1f5b74f6b2f8.png)

Version problem, request help！！！

**Comment by FN8087** [comment]
![image](https://user-images.githubusercontent.com/90084202/141397416-667e574a-6384-4210-94eb-495e0bb25e48.png)

**Comment by boyan01** [comment]
this plugin minimum depolyment target required macOS 10.12

Maybe you need upgrade you flutter app min depolyment target on macOS.

**Comment by FN8087** [comment]
> this plugin minimum depolyment target required macOS 10.12
> 
> Maybe you need upgrade you flutter app min depolyment target on macOS.

![image](https://user-images.githubusercontent.com/90084202/141466796-804f3a7f-7c5d-4aab-92a0-11fc473571ac.png)
![image](https://user-images.githubusercontent.com/90084202/141466962-bfee61e3-b12f-4506-be88-61daafbaf9cc.png)

**Comment by FN8087** [comment]
![image](https://user-images.githubusercontent.com/90084202/141467324-5958e68b-188d-4a92-b50a-59f03b45fe23.png)
