### ISSUE TITLE
[Feature] Proxy support

### ISSUE THREAD

**Issue by xweiba** [MixinNetwork/flutter-plugins#223]
Add a support to set a proxy server

**Comment by boyan01** [comment]
Sorry, I cann't understand this issue. 

closing....

**Comment by sh1man999** [comment]
up

**Comment by sh1man999** [comment]
Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", $"--proxy-server=\"{url}\"");
