### ISSUE TITLE
JavaScriptMessageHandler can not been trigered on  Windows Platform

### ISSUE THREAD

**Issue by RoleWong** [MixinNetwork/flutter-plugins#227]
I tend to trigger the postMessage with the following codes on HTML.

But those JavaScriptMessageHandlers on Dart can not been triggered.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/24520036/225538100-20ac6ae9-21c1-47c0-a9e8-67ad861421e3.png">

While this problems only occurs on Windows, but not macOS.

Found this PR https://github.com/MixinNetwork/flutter-plugins/pull/168, and I upgrade this package to to desktop_webview_window: ^0.2.0,  and the code downloaded do includes the added code from this PR, but this still can not work.

**_[Update1: ] It seems caused by the following `if`, that prevent the platfrom aprt from macOS to register the handler. Can I just remove this judgment logic?_**

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/24520036/225521169-488d9ce1-d345-4986-bb42-7fbaa6ae44a5.png">

**Comment by RoleWong** [comment]
**Solution found: In this case, postMessage should be called as window.chrome.webview.postMessage(val); . This issue can be cloused.**

**Comment by moodstubos** [comment]
@RoleWong thank you!
This helps a lot.
