### ISSUE TITLE
Microsoft Edge can not read and write on its data direcotry

### ISSUE THREAD

**Issue by RoleWong** [MixinNetwork/flutter-plugins#229]
After packing my Windows App to MSIX, it will be installed to `WindowsApps` directory as defult as an UWP application.

But, the content in `WindowsApps` directory can not beenwrote, so this error occurs when user tend to open this webview.

![企业微信截图_16789791205883](https://user-images.githubusercontent.com/24520036/225788846-19708cb4-4ca6-4a06-85e1-4381c67da603.png)

[Update]: I store the `userDataFolderWindows` to `Documents` manually.

**Comment by sundarlucifer** [comment]
@RoleWong I have the same problem. Can you please elaborate on
`I store the userDataFolderWindows to Documents manually.`
