### ISSUE TITLE
In windows can't delete desktop_lifecycle_plugin.dll

### ISSUE THREAD

**Issue by chifandeyu** [MixinNetwork/flutter-plugins#23]
In the windows desktop environment, an accidental appearance after quitting the example program cannot delete the desktop_lifecycle_plugin.dll

**Comment by boyan01** [comment]
I have also encountered this situation. But what is confusing is that the `UnhookWindowsHookEx` method has been executed when the plugin is destroyed. [detail](https://github.com/MixinNetwork/flutter-plugins/blob/db8b0bbb7e6c7fec5049ff85ae10e09dd4942b21/packages/desktop_lifecycle/windows/desktop_lifecycle_plugin.cpp#L108)

Do you have any ideas?

**Comment by boyan01** [comment]
Is that we should execute `UnhookWindowsHookEx` in `DllMain`'s `DLL_PROCESS_DETACH` event? https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain

**Comment by chifandeyu** [comment]
> I have also encountered this situation. But what is confusing is that the `UnhookWindowsHookEx` method has been executed when the plugin is destroyed. [detail](https://github.com/MixinNetwork/flutter-plugins/blob/db8b0bbb7e6c7fec5049ff85ae10e09dd4942b21/packages/desktop_lifecycle/windows/desktop_lifecycle_plugin.cpp#L108)
> 
> Do you have any ideas?

我目前没有好的方法，只能放弃使用全局钩子，导出DispatchApplicatinState函数提供给外部调用，直接在FlutterWindow::MessageHandler 调用了。
