### ISSUE TITLE
[desktop_multi_window] Is it possible to use platform channels in a multi window

### ISSUE THREAD

**Issue by pauli2406** [MixinNetwork/flutter-plugins#238]
Hi,
I noticed an issue it does not seem to be possible to call platform channels within a new window.
Is this assumption correct, and if is there a way to come around this issue?

This issue first came up while trying to use the following plugin in a new window.
More details to reproduce and the logs can be found in this issue: 
https://github.com/alexmercerind/media_kit/issues/161#issuecomment-1523389691

**Version (please complete the following information):**
 - Flutter Version: v3.7.9
 - OS: macOS
 - plugin: desktop_multi_window: ^0.2.0

**Comment by boyan01** [comment]
> Is it possible to use platform channels in a multi window

Yes, you can see here:
https://github.com/MixinNetwork/flutter-plugins/issues/58#issuecomment-1060371162

**Comment by pauli2406** [comment]
Thanks, it is now indeed working. 
maybe worth adding this as a hint in the readme :)

**Comment by pauli2406** [comment]
Sorry that this might be a bit off topic to the title but kind of still matches.
I just realised that the flutter lifecycle methods do not seem to be considered if a new window is closed. Is there also some configuration I need to do?

**Comment by pauli2406** [comment]
Nvm, managed to fix it.
The trick is to also add the dependency "window_manager"

Then extend  the main widget of the new window with WindowListener

```
class _MainWidgetState extends State<MainWidget> with WindowListener {

     @override
  void onWindowClose() async {
    // Execute the logic here instead of on dispose
    super.onWindowClose();
  }
}

```
