### ISSUE TITLE
[desktop_webview_window] Title bar is too big

### ISSUE THREAD

**Issue by lolocomotive** [MixinNetwork/flutter-plugins#247]
This is a screenshot of the example running in Ubuntu:
![image](https://github.com/MixinNetwork/flutter-plugins/assets/49951010/208370bb-95a8-4e6d-9032-0a266eae2630)
There shouldn't be this much space around the top bar. Is there any way to fix/work around this?

**Comment by lolocomotive** [comment]
For anyone wondering, I found a workaround.
https://github.com/lolocomotive/flutter-plugins/commit/b7b5b2af431ae23e6d9bb0b6c21a3503bf58b6e7
It is pretty ugly though and I think that to fix it properly, the flutter engine itself would have to be modified.
I'm not really sure since I don't have a lot of experience with GTK.
Since this is an ugly workaround and not a fix I'm only commenting here and not making a pull request.

**Comment by boyan01** [comment]
thanks for the report. already fixed in 7b3235fb79033dd7174b87fe654c1a9cf089d0b7 

I'll release a new version a bit later
