### ISSUE TITLE
Cannot compile desktop_webview_window on Linux

### ISSUE THREAD

**Issue by MuhammedKpln** [MixinNetwork/flutter-plugins#248]
Cannot compile, webkitgtk2-4.1 is already installed, 

Getting deprecated error on linux.
 
Using arch linux.

```error: 'webkit_web_view_run_javascript_finish' is deprecated: Use 'webkit_web_view_evaluate_javascript_finish' instead [-Werror,-Wdeprecated-declarations]```

Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d3d8effc68 (6 days ago) • 2023-05-16 17:59:05 -0700
Engine • revision b4fb11214d
Tools • Dart 3.0.1 • DevTools 2.23.1

**Comment by zoli** [comment]
@MuhammedKpln how did you got around this?

**Comment by MuhammedKpln** [comment]
They already published fix, use git version instead.

**Comment by MuhammedKpln** [comment]
> @MuhammedKpln how did you get around this?

They already published fix, use git version instead.
