### ISSUE TITLE
desktop_webview_window msix not working

### ISSUE THREAD

**Issue by millie-molly** [MixinNetwork/flutter-plugins#256]
It is perfectly working except packaged by msix.
A webView show up and just shut down

**Comment by josercc** [comment]
macos same

**Comment by millie-molly** [comment]
msix is microsoft store extension. so, msix has no connection with mac..

**Comment by boyan01** [comment]
Sorry for later.  document added. 57b6173972c63af4454ce95b39ceb1f3f9b2b6e8

you can use `WebviewWindow.create()` to create a webview with a custom user data folder.

```dart
final webview = await WebviewWindow.create(
  confiruation: CreateConfiguration(
    userDataFolderWindows: 'your_custom_user_data_folder',
  ),
);
```
