### ISSUE TITLE
[desktop_drop] Wrong path prefix on macOS

### ISSUE THREAD

**Issue by sxd1140** [MixinNetwork/flutter-plugins#26]
I got `file:///Users/xxx/dir` on macOS, expect `/User/xxx/dir`.

```
desktop_drop: 0.1.2   
Flutter 2.5.3
macOS 12.0.1
```

**Comment by boyan01** [comment]
you can use `Uri.toFilePath` to create a file path from a file URI

https://api.flutter.dev/flutter/dart-core/Uri/toFilePath.html

**Comment by sxd1140** [comment]
I know can workaround this, but package provide platform specific style is better.

**Comment by crossle** [comment]
file:// is better

**Comment by crossle** [comment]
file:// is better
