### ISSUE TITLE
Example desktop_webview_window is running on a Mac, the memory has not been released

### ISSUE THREAD

**Issue by zobinimmx** [MixinNetwork/flutter-plugins#263]
**Is there an existing issue for this?**
 I have searched the [existing issues](https://github.com/flutter/flutter/issues)

**Steps to reproduce**
this demo can reproduce
https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_webview_window

**Expected results**
webview window can release normal

**Actual results**
memory has not been released

**Flutter Doctor output**
[✓] Flutter (Channel beta, 3.12.0-1.1.pre, on macOS 13.1 22C65 darwin-arm64, locale ja-CN)
    • Flutter version 3.12.0-1.1.pre on channel beta at /opt/homebrew/Caskroom/flutter/3.3.10/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e2e0aa7037 (3 weeks ago), 2023-06-20 19:48:59 -0700
    • Engine revision 45712dd2f1
    • Dart version 3.1.0 (build 3.1.0-163.1.beta)
    • DevTools version 2.24.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/qq/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] VS Code (version 1.76.2)
    • VS Code at /Users/qq/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is ::1,localhost,127.0.0.1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

**The result of running with Xcode**
**Step1**
Run the example
![image](https://github.com/MixinNetwork/flutter-plugins/assets/139520695/6d66470a-a06d-4706-beba-cb0099e32492)

**Step2**
Open the webview window,Memory has increased
![image](https://github.com/MixinNetwork/flutter-plugins/assets/139520695/c8390e06-c470-4d64-871b-f8bfc0da7a67)

**Step3**
Close the webview window, memory not released
![image](https://github.com/MixinNetwork/flutter-plugins/assets/139520695/7eaf70a9-8fbe-4b1e-a9b7-be7abf25b997)

**Step4**
Open again
![image](https://github.com/MixinNetwork/flutter-plugins/assets/139520695/b07e091d-48a0-4b64-a032-a2f3e6445a53)

**Step5**
Close
![image](https://github.com/MixinNetwork/flutter-plugins/assets/139520695/a1561c0d-58c8-4fff-81bb-4a82de3bf39d)

**How can I release the memory?**

**Comment by hyungtaecf** [comment]
Yes, I noticed it creates a new isolate every time it spawns a window but it doesn't kill the isolate after closing the window... I couldn't find in the code from Webview, WebviewImpl and WebviewWindow where it creates the isolate... But it seems to be removing properly the webviews from the "List<WebviewImpl> _webviews" variable (while keeping their processes) when using the "close" method...

**Comment by zobinimmx** [comment]
When the window is closed, the webview in the "List _webviews" is indeed remove. 
How can I release the memory usage related to webview when the webview is remove.
No clue at all.

**Comment by boyan01** [comment]
thanks for the report, fixed by 1c89d4e0cdc5035a334245d638e99923fa89c929
