### ISSUE TITLE
macOS 11.5.1 flutter 2.5.3

### ISSUE THREAD

**Issue by FN8087** [MixinNetwork/flutter-plugins#27]
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `desktop_webview_window` from `Flutter/ephemeral/.symlinks/plugins/desktop_webview_window/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "desktop_webview_window":
      In Podfile:
        desktop_webview_window (from `Flutter/ephemeral/.symlinks/plugins/desktop_webview_window/macos`)

    Specs satisfying the `desktop_webview_window (from `Flutter/ephemeral/.symlinks/plugins/desktop_webview_window/macos`)` dependency were found, but they
    required a higher minimum deployment target.

**Comment by boyan01** [comment]
desktop_webview_window require project build target min to macos 10.12.

https://github.com/MixinNetwork/flutter-plugins/blob/main/packages/desktop_webview_window/macos/desktop_webview_window.podspec#L19
