### ISSUE TITLE
The mess of packages here is terrible. Please separate packages into their own repositories!

### ISSUE THREAD

**Issue by Nashev** [MixinNetwork/flutter-plugins#273]
Issues for each package must not be in a single list! Pull requests also.

**Comment by boyan01** [comment]
We only have one person maintaining these plugins, and splitting them up would add extra work for us.

**Comment by Nashev** [comment]
I know it's extra work. But how do you live in this mess?..

**Comment by crossle** [comment]
This library like https://github.com/flutter/packages/tree/main/packages, include some plugins in one repo
