### ISSUE TITLE
[desktop_drop] error C2220: cpp compile error

### ISSUE THREAD

**Issue by mhkarami** [MixinNetwork/flutter-plugins#278]
i used this library on flutter `v3.7.0` without any problem for windows platform.
but when i upgrade to` v3.13.0` i faced this error : (also on `v3.10.6` and beta  `v3.14.0-0.1.pre` have same error )

```
[my_project_path]\windows\flutter\ephemeral\.plugin_symlinks\desktop_drop\windows\desktop_drop_plugin.cpp(150): error C2220: the following warning is treated as an error [[my_project_path]\build\windows\plugins\desktop_drop\desktop_drop_plugin.vcxproj]
[my_project_path]\windows\flutter\ephemeral\.plugin_symlinks\desktop_drop\windows\desktop_drop_plugin.cpp(150): warning C4701: potentially uninitialized local variable 'hwnd' used [[my_project_path]\build\windows\plugins\desktop_drop\desktop_drop_plugin.vcxproj]
[my_project_path]\windows\flutter\ephemeral\.plugin_symlinks\desktop_drop\windows\desktop_drop_plugin.cpp(150): warning C4703: potentially uninitialized local pointer variable 'hwnd' used [[my_project_path]\build\windows\plugins\desktop_drop\desktop_drop_plugin.vcxproj]
Exception: Build process failed.
```
i tried these solutions :
- delete windows folder and create again by `flutter create --platforms=windows,web .`
- delete build folder
- change `sdk` - it woks on `3.7.0`
- `flutter clean` and `flutter pub cash restore `
- update `visual studio community 2022` and `visual studio build tools 2019` to latest version 
- visual studio build tools config :
![image](https://github.com/MixinNetwork/flutter-plugins/assets/50570349/692907b4-94db-405e-8a24-125cf050706b)

**Comment by czw299** [comment]
Same. This problem should occur in desktop_drop 0.4.2. I change the code in desktop_drop_plugin.cpp 
from:
`
HWND hwnd;
if (registrar->GetView()) {
  hwnd = registrar->GetView()->GetNativeWindow();
}
`
to:
`HWND hwnd = registrar->GetView()->GetNativeWindow();`

Now it works for me. But I don't know if this will lead to other unknown problems.

**Comment by HasanEltantawy** [comment]
I have the same problem here but in debug mode only and when switch to release mode the problem gone

**Comment by HasanEltantawy** [comment]
Using this line I managed to disable warnings shown in debug console
```c++
#pragma warning(disable : 4701 4703)
```

Put this line above this method
```c++
#pragma warning(disable : 4701 4703)
    void DesktopDropPlugin::RegisterWithRegistrar(
        flutter::PluginRegistrarWindows *registrar)
    {
        auto channel =
            std::make_unique<flutter::MethodChannel<flutter::EncodableValue>>(
                registrar->messenger(), "desktop_drop",
                &flutter::StandardMethodCodec::GetInstance());

        HWND hwnd;
        if (registrar->GetView())
        {
            hwnd = registrar->GetView()->GetNativeWindow();
        }

        channel->SetMethodCallHandler([](const auto &call, auto result)
                                      { result->NotImplemented(); });

        auto drop_target = new DesktopDropTarget(std::move(channel), hwnd);

        auto plugin = std::make_unique<DesktopDropPlugin>(drop_target);

        registrar->AddPlugin(std::move(plugin));
    }
 ```
 
 in 
`<project_name>\windows\flutter\ephemeral\.plugin_symlinks\desktop_drop\windows`

**Comment by boyan01** [comment]
Thanks for the detailed issue. I'll release an other version to pub.dev lately.
