### ISSUE TITLE
http://localhost on macOs

### ISSUE THREAD

**Issue by sinapsi** [MixinNetwork/flutter-plugins#29]
if i try to see http://localhost pages (served by shelf) i have a blank page and these xcode logs:

<desktop_webview_window.WebviewWindowController: 0x6000006b91e0> deinited
"load url: http://localhost/"
2021-11-29 18:07:15.179862+0100 elios_viewer_mac[21196:4026205] [Process] 0x7fd5cd0f2220 - [pageProxyID=23, webPageID=24, PID=21403] WebPageProxy::didFailProvisionalLoadForFrame: frameID = 3, domain = NSURLErrorDomain, code = -1022
flutter: args: [web_view_title_bar, 2, 24]
flutter: runWebViewTitleBarWidget: 2, 24

i think it's a security problem, is there a way to let it work from flutter? is it a macOs setting?

**Comment by boyan01** [comment]
Did you try add NSAllowsArbitraryLoadsInWebContent To your macOS/runner/
Info.plist?
https://github.com/MixinNetwork/flutter-plugins/blob/main/packages/desktop_webview_window/example/macos/Runner/Info.plist#L5-
L9

Michele Rappazzo ***@***.***>于2021年11月30日 周二上午1:12写道：

**Comment by sinapsi** [comment]
Thank you, that helped ^_^

**Comment by d3roch4** [comment]
Dont work for me :-(
 ```
Inspection is enabled by default for process or parent application with 'com.apple.security.get-task-allow' entitlement linked against old SDK. Use `inspectable` API to enable inspection on newer SDKs.
<desktop_webview_window.WebviewWindowController: 0x600003426260> deinited
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(0, can not find webview for id: 0, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      WebviewImpl.launch (package:desktop_webview_window/src/webview_impl.dart:125:5)
<asynchronous suspension>
```
