### ISSUE TITLE
Remove dependency from WakeLock

### ISSUE THREAD

**Issue by NickNevzorov** [MixinNetwork/flutter-plugins#294]
The wakelock package is no longer supported and is outdated, because of it it is not possible to use new plugins and the new version of the platform

Remove dependency from wakelock, please, or use a new wakelock_plus ( https://pub.dev/packages/wakelock_plus )

Thank you!

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

**Comment by boyan01** [comment]
Thanks for the reminder. But I can not remenber and find which plugin depends on `wakelock` pakcage. 

Can you give me more details ?

**Comment by NickNevzorov** [comment]
Sorry, If I create a new flutter project all ok. 

In my project after add desktop_drop, wakelock is included. I think is my issue, I trying to solve
