### ISSUE TITLE
[desktop_webview_window] How can I listen to url changes

### ISSUE THREAD

**Issue by 3rpse-ai** [MixinNetwork/flutter-plugins#31]
First of all big thanks for the plugin! I would like to use it for an authentication flow in which I have to fetch a secret from a callback url. In order to do that I would need to be able to listen to url changes to identify the callback url and extract the secret.

I tried to find a way to implement that with this plugin but had no success so far. Could you maybe point me to a solution for that?

**Comment by boyan01** [comment]
I tried to add `addOnUrlRequestCallback` api for Webview. Hope to meet your needs.

**Comment by 3rpse-ai** [comment]
Thank you very much!! When will version 0.1.5 be available via pub.dev?

**Comment by boyan01** [comment]
soon. I’ll publish this  in next Monday

Felix Weickert ***@***.***>于2021年12月11日 周六下午5:59写道：

**Comment by 3rpse-ai** [comment]
thank you!
