### ISSUE TITLE
desktop_drop not working on web-renderer canvaskit

### ISSUE THREAD

**Issue by RoyalCoder88** [MixinNetwork/flutter-plugins#322]
Hi, thanks for your great plugin, please help me with this issue: when my web app is built with **enderer canvaskit**   - **desktop_drop** doesn't work at all, can you guide me on how to fix it in **renderer canvaskit**

Thanks in advance!

**Version (please complete the following information):**
  • Flutter version 3.19.3 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (2 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    •plugin: [e.g. desktop_drop: 0.4.4

**Comment by jackie099** [comment]
Try #323
