### ISSUE TITLE
[desktop_drop] macos file path need support bookmark in sandbox mode

### ISSUE THREAD

**Issue by izouxv** [MixinNetwork/flutter-plugins#329]
if the app need distubite on app store, 
the app MUST support sandbox mode, 
all file path need use book mark to reuse
[apple book mark](https://developer.apple.com/documentation/professional_video_applications/fcpxml_reference/asset/media-rep/bookmark/using_bookmark_data)

the desktop-drop get the file path(URL), it works
but if the app restart, the app use the the path(URL) again, it's not working

so, in sandbox. the desktop-drop get the file path(URL), and it need to get the file bookmak,  
app should save the bookmark for next using. 

``` 
var isStale: Bool = false 
let file_url = try! URL(resolvingBookmarkData: bookmark, bookmarkDataIsStale: &isStale) 
let suc = file_url.startAccessingSecurityScopedResource()
//the file_url is works
```

**Comment by boyan01** [comment]
should fixed by #330
