### ISSUE TITLE
[desktop] android gradle version

### ISSUE THREAD

**Issue by boyan01** [MixinNetwork/flutter-plugins#350]
A few things to consider:

- I would suggest using `./gradlew wrapper --gradle-version=8.8` instead of changing the number directly in `gradle/wrapper/gradle-wrapper.properties` as this will update `gradlew`, `gradlew.bat` and the JAR file `gradle/wrapper/gradle-wrapper.jar`
- I would also suggest using the same Kotlin version and Android Gradle Plugin (AGP) as the latest one tested by the Flutter Team, updating Kotlin requires projects to the Kotlin version in the `android` platform project, we should consider using `1.7.10` for compatibility in case we don't use Kotlin language features above this version, updating Android Gradle Plugin cause many unexpected issues in Release Build, I wasn't able to detect what caused the issues, crashes and startup issues until I removed the `android` project, recreate it and move my changes, after some manual debugging it seems the issue that I updated Kotlin and AGP to the latest version, though I also did this in the blank Flutter project without any issues, so it might cause those issues with another plugin or more advance use cases, at the time of this PR, Flutter docs hasn't documented this common issue, in new releases (3.16 or 3.21), they will give you a warning when building the project to avoid such issues.

_Originally posted by @EchoEllet in https://github.com/MixinNetwork/flutter-plugins/issues/155#issuecomment-2223671370_

**Comment by EchoEllet** [comment]
Thank you for your consideration. 

Already created a branch in my fork addressing those. haven't sent it yet.

**Comment by boyan01** [comment]
completed by #351
