### ISSUE TITLE
desktop_webview_window is having some issues in windows 10 (I'm using msix)

### ISSUE THREAD

**Issue by nikirana22** [MixinNetwork/flutter-plugins#378]
I'm providing a path in CreateConfiguration which is ('${Platform.environment['AppData']}\\A') i'm creating this dir in main method 
it is working fine in windows 11 but In windows 10 folder is storing in C:\Users\username\AppData\Roaming\A

**Comment by boyan01** [comment]
This issue seems not relate plugin, but for windows.

according doc, the`$env:APPDATA` is`C:\Users\<username>\AppData\Roaming`

https://learn.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables#variables-that-are-recognized-only-in-the-user-context
