### ISSUE TITLE
How do I access File bytes and metadata when it is dropped?

### ISSUE THREAD

**Issue by BirjuVachhani** [MixinNetwork/flutter-plugins#39]
It is very crucial to allow access of file bytes and metadata like name, size, extension, etc for it to be usable properly. Our app uses `drop_zone` for web and it allows us to access `html.file` which is not ideal as it should be abstracted away behind a platform but it still makes our job easier.

I tried the web support of this package and came to know that it only provides blob uri which is not much useful. I tried to look into ways of retrieving file bytes and metadata from it but I couldn't. 

A possible solution could be abstracting away the file implementation by creating a platform independent `File` class that allows to access various file properties and bytes. This allows to use it on any platform.

`file_picker` plugin seems to do the same thing and it is quite convenient.

These could be the basic info any app/developer would want to access.

- **File bytes:** to send it to some server.
- **FIle name:** to display it in the UI.
- **File extension:** Useful for filtering out supported files/
- **File size:** Useful for showing uploading percentage indicator in UI. Also useful to tell whether file is empty or not.
- **File path:** (if possible): Could useful to show in UI in some cases.

If this package can support this, it would a huge help to any developers out there.

**Comment by boyan01** [comment]
Thanks a lot for detailed description.

For web.  
* read bytes. `XFile(uri.path)` should be worked , but it seems that can not get the real  file name. That should be a bug.
* File path. I can not find a way to get the real file path on Web...
* File size.  maybe XFile also worked.


I think we should replace the drag done result type from  Uri to XFile.

relate issue.
https://github.com/MixinNetwork/flutter-plugins/issues/26
https://github.com/MixinNetwork/flutter-plugins/issues/15

**Comment by BirjuVachhani** [comment]
That would be great. Thanks.
