### ISSUE TITLE
[desktop_drop] Expose pointer coordinates when files are dropped

### ISSUE THREAD

**Issue by BirjuVachhani** [MixinNetwork/flutter-plugins#4]
It would be awesome if `onDragDone` could provide the pointer location on the screen. The usecase is for drawboard applications like Figma or Adobe XD where it allows to drag and drop images and shows them at pointer location.

e.g.

```dart
onDragDone: (List<Uri> urls, Offset position) {
  // dx = x coordinate
 // dy = y coordinate
}
```

**Comment by boyan01** [comment]
Good idea. maybe other callback such as `onDragEntered` and `onDragExited` can also provide a pointer location.

**Comment by BirjuVachhani** [comment]
Yeah. I did build a prototype for this which I tested on Windows, Mac and web. Although there is this 1 problem with Windows that I faced. The pointer location that Windows provides is of a virtual space in multi monitor setup. So all the displays creates one unified virtual display coordinating system which might lead to a pointer location out of the bounds of screen size.

I may be different in your implementation so I am not 100% sure! However I can't test the same as do not have multiple displayes now.

**Comment by BirjuVachhani** [comment]
@boyan01 That's great. I'll take a look later to see what I might have done wrong, 😅 Thanks for this.

**Comment by boyan01** [comment]
Introducing a new version：

```
desktop_drop: ^0.1.0
```

Which exposed the local and global position in `onDragEntered `, `onDragExited ` ,`onDragDone ` and `onDragUpdate` callbacks.

Thanks for your proposal.

**Comment by BirjuVachhani** [comment]
@boyan01 That's awesome. Thanks for this! 🚀
