### ISSUE TITLE
[pasteboard] Web Support

### ISSUE THREAD

**Issue by BirjuVachhani** [MixinNetwork/flutter-plugins#43]

**Comment by boyan01** [comment]
web actually not need this plugin, because Dart can access `html.window` and `html.document` directly.

**Comment by BirjuVachhani** [comment]
Yeah, but it is not a universal way. This would require extra `kIsWeb` checks and html import is not ideal for cross platform app. It would be much appreciated if this package did support it in a universal API for all platforms.

**Comment by boyan01** [comment]
closed by https://github.com/MixinNetwork/flutter-plugins/commit/e700e38540c52846615b5388c06ce44889f7e7d9

included in https://pub.dev/packages/pasteboard/versions/0.1.0
