### ISSUE TITLE
[desktop_drop] spaces in pathname leads to bad instantiation of XFile

### ISSUE THREAD

**Issue by pakopako-d** [MixinNetwork/flutter-plugins#53]
https://github.com/MixinNetwork/flutter-plugins/blob/556a285a61f43b70f028038fb8302d970f91745a/packages/desktop_drop/lib/src/channel.dart#L88

If there are spaces in the path name of the file you are dropping, they get converted to %20.  When making a new XFile on line 88, the %20 causes Exceptions (os error, file not found) when trying to look up details such as file length and modification time.  If %20 is replaced with spaces here, then the XFile will have a valid path and not cause Exceptions when looking up file details.
```dart
 files: paths.map((e) => XFile(e.replaceAll('%20', ' '))).toList(),
```
There is probably a more elegant solution than this, and I have only tested on a Linux desktop.

**Comment by boyan01** [comment]
Thanks for your detailed feedback, already fixed in latest version: https://pub.dev/packages/desktop_drop
