### ISSUE TITLE
[pasteboard] How to listen to clipboard paste events?

### ISSUE THREAD

**Issue by BirjuVachhani** [MixinNetwork/flutter-plugins#57]
Is there a way to listen to clipboard paste events and then read image? How do I use this plugin in situation where whenever an image is pasted from clipboard, I need a callback to handle the event?

**Comment by boyan01** [comment]
You can use `SingleActivator` or something else ( like a button ) to interact with user and then get the data from clipboard.

It there any system give a event callback for clipboard?

**Comment by BirjuVachhani** [comment]
Web provides this:
```dart
html.document.onPaste.listen(onPasteEvent);
```

I think flutter should also have something similar to listen to paste events.

**Comment by boyan01** [comment]
This seems belong to the flutter framework.

**Comment by BirjuVachhani** [comment]
Yes, it does. I am not sure how but it would be great to have something similar for desktop platforms as well.
