### ISSUE TITLE
[desktop_multi_window] In the created window can not call other plugins

### ISSUE THREAD

**Issue by SiongSng** [MixinNetwork/flutter-plugins#58]
In the created window can not call other plug-ins, it will throw MissingPluginException, but the main window can be called.

operating system: ubuntu 21.10

**Comment by SiongSng** [comment]
I found the solution

**Comment by cbenhagen** [comment]
@SiongSng what was the solution?

**Comment by SiongSng** [comment]
@cbenhagen 
This is the solution, manually register each plugin here

Windows: https://github.com/MixinNetwork/flutter-plugins/blob/65dcbb02d6433205e689e83214506898d89d8247/packages/desktop_multi_window/example/windows/runner/flutter_window.cpp#L32
Linux: https://github.com/MixinNetwork/flutter-plugins/blob/65dcbb02d6433205e689e83214506898d89d8247/packages/desktop_multi_window/example/linux/my_application.cc#L65
macOS: https://github.com/MixinNetwork/flutter-plugins/blob/65dcbb02d6433205e689e83214506898d89d8247/packages/desktop_multi_window/example/macos/Runner/MainFlutterWindow.swift#L15

**Comment by provokateurin** [comment]
So what I did was just calling

https://github.com/MixinNetwork/flutter-plugins/blob/833cda265f2b2e9fe4105d4c56386c5ccd82464a/packages/desktop_multi_window/example/linux/flutter/generated_plugin_registrant.cc#L12

inside

https://github.com/MixinNetwork/flutter-plugins/blob/833cda265f2b2e9fe4105d4c56386c5ccd82464a/packages/desktop_multi_window/example/linux/my_application.cc#L65-L69

and it just works. No need to specify each plugin manually. I guess the same can be done for macOS and Windows.

**Comment by sornian** [comment]
I try use this way ，but it's not useable yet。
os :ubuntu 24
flutter:3.24
