### ISSUE TITLE
Add support for grabbing cookies

### ISSUE THREAD

**Issue by mahediotto** [MixinNetwork/flutter-plugins#59]
I want to grab the cookies from the loaded page with the package desktop_webview_window: ^0.1.6 . Request you to add a function for it.

**Comment by boyan01** [comment]
Sorry, We do not accept requests for new plugins from the community at now. If you need a flutter function or some features, please go to the[ flutter/flutter](https://github.com/flutter/flutter/issues) to submit a request.
