### ISSUE TITLE
[desktop_webview_window] Exception when close webview and create again

### ISSUE THREAD

**Issue by dodatw** [MixinNetwork/flutter-plugins#61]
We found a exception when we cann webview.close then call webview.create.
I can reproduce this issue on macos on 0.16
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(0, can not find webview for id: 0, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
```

**Comment by boyan01** [comment]
This exception happened when you try to use a closed WebView window.

I could not reproduce this exception based your description.


> We found a exception when we cann webview.close then call webview.create.

Can your provider more detailed information for this ? or provider the reproducable code?

**Comment by dodatw** [comment]
I call
```
webview.close();
webview = await WebviewWindow.create();
```
I call create after close immidiately, is close() is an async call ?

**Comment by dodatw** [comment]
Thanks a lot, useful infomation.
Adter add wait until onClose.whenComplete, this issue gone!
