### ISSUE TITLE
[desktop_webview_window] 可以让它当成控件使用吗?

### ISSUE THREAD

**Issue by igufei** [MixinNetwork/flutter-plugins#62]
可以让[desktop_webview_window] 当成控件显示在主界面 吗?我不想让它显示 在一个独立的窗口,类似于c#的cefsharp,可以放在winform的panel里使用

**Comment by boyan01** [comment]
No, that is impossible now.  Duplicate of #30

You can track this issue for more information. https://github.com/flutter/flutter/issues/37597
