### ISSUE TITLE
[win_toast] Not working on Windows 10 after installation

### ISSUE THREAD

**Issue by Yanis01** [MixinNetwork/flutter-plugins#64]
Hello,
I developed a flutter app for Windows 10 and I am using win_toast for the notification.
It seemed to be working fine while I was developing, but after I installed the application with the msix the notifications are not working anymore.
I can still see the image and the text but the action buttons do not appear anymore and the title of the notification is not the one that should be displayed, instead I see the identifier of the app with a code as you can see in the image below.

![notification_win_toast](https://user-images.githubusercontent.com/28342348/153372443-5e89545d-d9b3-450d-b89a-2112b1416de2.png)

**Comment by sidevesh** [comment]
Facing the same issue, I think this might be happening because `win_toast` is for Win32 apps and it requires AUMID and some other properties set on the shortcut file which, in case of msix packaging is not created.

**Comment by sidevesh** [comment]
@Yanis01 were you able to solve the issue ?

**Comment by boyan01** [comment]
should fixed by #142
