### ISSUE TITLE
[desktop_multi_window] Opening a new window on macOS is a blank window

### ISSUE THREAD

**Issue by SiongSng** [MixinNetwork/flutter-plugins#65]
## Code
[packages/desktop_multi_window/example](https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_multi_window/example)
## Screenshot
![image](https://user-images.githubusercontent.com/48402225/153735261-cac9a9c3-088a-46ad-a78a-cdbb065393cb.png)

**Comment by boyan01** [comment]
I tested on flutter latest master and stable channel, the example works fine.


It there any more information you can paste here? for example: flutter version, system version, error log.

**Comment by SiongSng** [comment]
![VirtualBox_macOS_13_02_2022_10_10_28](https://user-images.githubusercontent.com/48402225/153738401-5c254ca9-2681-46bc-94b8-4c1b96690ac1.png)
I restarted the computer and it was fine
