### ISSUE TITLE
event widget

### ISSUE THREAD

**Issue by BerlinLion** [MixinNetwork/flutter-plugins#67]
Where is event_widget.dart located or how can I install it? It's mentioned in the imprt-section as the last import, in the example code, but I can't find any related file to that neither inside the project nor on pub-dev nor on google.

**Comment by boyan01** [comment]
Do you means this file in example?

https://github.com/MixinNetwork/flutter-plugins/blob/556a285a61/packages/desktop_multi_window/example/lib/event_widget.dart
