### ISSUE TITLE
Do you have plans for desktop_drag?

### ISSUE THREAD

**Issue by longtimedeveloper** [MixinNetwork/flutter-plugins#69]
Are there plans for implementing desktop dragging of content outside of the window?

Scenario:  I have an app that I need to be able to drag text from the Flutter desktop app to another desktop application that is a drop target; the drop target is a text field in a browser window.

Other drag scenarios could be images as well as text.

I'm doing this in a C# WPF app that I use every day that I'm converting to Flutter.  This is the last feature I've not been able to figure out how to do.

Thank you and have a great day, Karl

**Comment by boyan01** [comment]
Sorry, there is no plan to implement which drag view from flutter to another application.

And Sorry again, We do not accept requests for new plugins from the community at now. If you need a flutter function or some features, please go to the[ flutter/flutter](https://github.com/flutter/flutter/issues) to submit a request.
