### ISSUE TITLE
pasteboard atlimage.h error

### ISSUE THREAD

**Issue by androidwoman** [MixinNetwork/flutter-plugins#75]
\appname\windows\flutter\ephemeral\.plugin_symlinks\pasteboard\windows\pasteboard_plugin.cpp(8,10): fatal error C1083: Cannot open include file: 'atlimage.h': No such file or directory [F:\appname\build\windows\plugins\pasteboard\pasteboard_plugin.vcxproj] 
Exception: Build process failed.

**Comment by keanallen** [comment]
Same issues here. How to fix this?

**Comment by keanallen** [comment]
Ok. I got it working by commenting/disabling the `altImage.h` import located in `D:\flutter\echat\windows\flutter\ephemeral\.plugin_symlinks\pasteboard\windows\pasteboard_plugin.cpp`

![image](https://user-images.githubusercontent.com/45480782/160024200-d3630141-1169-4bf3-84e6-94211e296a9f.png)

**Comment by boyan01** [comment]
@keanallen Thanks for the tip.  So I removed this unused import header.
