### ISSUE TITLE
close window error

### ISSUE THREAD

**Issue by guoyanyunyan666** [MixinNetwork/flutter-plugins#82]
Embedder did not return a valid render target.
Could not create the embedder backing store
![1647945153545_3ED4CA09-3FC4-4E59-A23F-374B99B1761D](https://user-images.githubusercontent.com/50606409/159462553-d734e9d4-f47d-4b35-acb3-c083088a7ffb.png)
.

**Comment by boyan01** [comment]
this seems also fixed by https://github.com/MixinNetwork/flutter-plugins/commit/f33938c8057024cc2bb27c999959d72b15980287
