### ISSUE TITLE
Problem to play ogg opus

### ISSUE THREAD

**Issue by rafaellfmachado** [MixinNetwork/flutter-plugins#84]
I have a problem to play a audio

is loading in exemple

https://filesmix.nyc3.digitaloceanspaces.com/sistema/2218/e1204c2596638bf6076bef8b824609b68b86e61c/1648126293-blob.ogg

**Comment by boyan01** [comment]
Tried playing this audio on a Mac and seems worked fine.

maybe the example app has limited permission to directory`~/Download`? did you try move you sound file to another directory which app has permission to read.

**Comment by rafaellfmachado** [comment]
I tested it with your example, I put the file in oasta audios, with my file it doesn't work, it doesn't even load the player, the loading circle remains, I'm testing it directly on my iphone device.

**Comment by rafaellfmachado** [comment]
https://user-images.githubusercontent.com/16171818/160052770-5fcd54a9-78ea-456a-a06e-a32759fa7974.MOV

**Comment by boyan01** [comment]
> with my file it doesn't work, it doesn't even load the player

Loading because example can not copy the audio assets to temp directory.

 Can you just rename you file to `test.ogg` and put it to `example/audios`?

**Comment by rafaellfmachado** [comment]
Actually, I renamed the file to test.ogg and it worked, but with another name it doesn't work, even changing , in the file

example
  final dest = File(p.join(dir.path, "audio1.ogg"));

and

final bytes = await rootBundle.load('audios/audio1.ogg');

And the file is in the right folder.

**Comment by boyan01** [comment]
Did you add the new file path to the assets in `pubspec.yaml` ?

https://github.com/MixinNetwork/flutter-plugins/blob/5d0a12ee4d77ea10f22a840248ae4c908b8bb128/packages/ogg_opus_player/example/pubspec.yaml#L69-L70
