### ISSUE TITLE
[desktop_multi_window] Passing data back to parent window

### ISSUE THREAD

**Issue by jason4012** [MixinNetwork/flutter-plugins#88]
On the windows version, I would like to pass data back to the parent window from a created multi_window instance. Is there a limitation in the engine itself that prevents me from modifying the C++ code, or is it just not implemented yet?

**Comment by boyan01** [comment]
you can use `DesktopMultiWindow.invokeMethod`. the parent window id always be 0.

 https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_multi_window#invoke-remote-window-method

**Comment by jason4012** [comment]
I tried doing that, but I got ```Unhandled Exception: MissingPluginException(No implementation found for method <method name> on channel mixin.one/flutter_multi_window_channel)``` - in this case I used the same logic that I used for sending data to the multi_window.

The notes in https://github.com/MixinNetwork/flutter-plugins/blob/main/packages/desktop_multi_window/lib/desktop_multi_window.dart#L53-L57 seem indicate that it's not possible to do this?

**Comment by boyan01** [comment]
You can try the example. 

there is a video which send message between main and child windows.

https://user-images.githubusercontent.com/17426470/160977327-c4eb7dd6-327c-4105-bcd9-ea1cc641512e.mov

**Comment by jason4012** [comment]
I am very confused because I can send messages from id ```0``` to id ```1``` but not vice versa. But the demo video indicates sending data from 1 --> 0? I tried running ```flutter clean``` and rebuilding from scratch, but that did not fix the issue either.

**Comment by jason4012** [comment]
Is this confirmed to work on windows? It seems the demo is on macos.

**Comment by jason4012** [comment]
Took some trial and error, but I was able to figure out the issue. If anyone else runs into this problem, make sure in your ```flutter_window.cpp``` file where you're registering plugins, that you do **not** register the DesktopMultiWindowPlugin. You should register the lifecycle plugin if you're using it, however.

**Comment by 308626712** [comment]
very useful
