### ISSUE TITLE
Not work on windows10

### ISSUE THREAD

**Issue by sunjianan9900** [MixinNetwork/flutter-plugins#9]
It works on mac
But can not drags on windows
![image](https://user-images.githubusercontent.com/10936316/136494447-ed5a3c67-77c3-4183-af52-274009cf490a.png)

**Comment by boyan01** [comment]
Does the `example` works on your devices? https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_drop/example

**Comment by boyan01** [comment]
It works on my windows device ( not virtual machine). 

Is there any error log when you launch example app ? ( such as `RegisterDragDrop failed:`)

**Comment by sunjianan9900** [comment]
> It works on my windows device ( not virtual machine).
> 
> Is there any error log when you launch example app ? ( such as `RegisterDragDrop failed:`)

thanks for your replay
it's very clean on log

But when I package release exe , it works
And then I open the exe on debug files , it works well

But still not work on "flutter run" model

but it's ok for me
