### ISSUE TITLE
CocoaPods could not find compatible versions

### ISSUE THREAD

**Issue by odejinmi** [MixinNetwork/flutter-plugins#90]
CocoaPods could not find compatible versions for pod "desktop_webview_window":
  In Podfile:
    desktop_webview_window (from `Flutter/ephemeral/.symlinks/plugins/desktop_webview_window/macos`)

Specs satisfying the `desktop_webview_window (from `Flutter/ephemeral/.symlinks/plugins/desktop_webview_window/macos`)` dependency were found, but they required a higher minimum deployment target.

**Comment by boyan01** [comment]
seems duplicate of https://github.com/MixinNetwork/flutter-plugins/issues/32

Can you take a try with https://github.com/MixinNetwork/flutter-plugins/issues/32#issuecomment-986860258
