### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by odejinmi** [MixinNetwork/flutter-plugins#91]
this is the error i got wen ever  i try to launch the window webview
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:71:9)
<asynchronous suspension>
#2      PermissionActions.request (package:permission_handler/permission_handler.dart:44:31)
<asynchronous suspension>
#3      FuturePermissionStatusGetters.isGranted (package:permission_handler_platform_interface/src/permission_status.dart:90:40)
<asynchronous suspension>

**Comment by boyan01** [comment]
Due to the limit of flutter , you can not use method channel in widget which run by `runWebViewTitleBarWidget`.

**Comment by chrissnyman** [comment]
> Due to the limit of flutter , you can not use method channel in widget which run by `runWebViewTitleBarWidget`.

Does this limitation apply to any plugin that uses method channel?

I am unable to use any plugin that will assist with removing the titlebar on the 2nd window

Any suggestions would be appreciated
